name: TabListEnhanced
version: '${project.version}'
main: club.cookie.tablistenhanced.TabListEnhanced
api-version: 1.18
softdepend: [EZRanksPro, PlaceholderAPI]
commands:
  tablistenhanced:
    description: Main command for TabListEnhanced
    usage: /<Command>
  tlp:
    description: Main command for TabListPro
    usage: /<Command>
    aliases: [tablistenhanced]
permissions:
  tablistenhanced.set:
    description: Permission to use /tablistedit set
    default: op
  tablistenhanced.reload:
    description: Permission to use /tablistedit reload
    default: op